mods:
  cmdrunner:
    args: ['uptime']
    refreshInterval: 5
    window: {x: 50, y: 3, w: 50, h: 3}
  clock:
    #type: clock
    format: "%H:%M:%S"
    refreshInterval: 1
    window: {x: 2, y: 3, w: 15, h: 5}
    # border: False
  clock2:
    type: clock
    format: "%H:%M:%S"
    refreshInterval: 1
    window: {x: 20, y: 3, w: 15, h: 5}
  my_clock2:
    type: clock
    title: ''
    format: "aa%H:%M:%S"
    refreshInterval: 1
    window: {y: 10, w: 15, h: 5}
  my_clock4:
    type: clock
    title: Services
    format: "aa%H:%M:%S"
    refreshInterval: 1
    window: {x: 20, y: 10, w: 30, h: 5}