# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: PyDashboard
site_url: https://a13ssandr0.github.io/pydashboard
repo_name: a13ssandr0/pydashboard
repo_url: https://github.com/a13ssandr0/pydashboard
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    note: fontawesome/solid/note-sticky
    abstract: fontawesome/solid/book
    info: fontawesome/solid/circle-info
    tip: fontawesome/solid/bullhorn
    success: fontawesome/solid/check
    question: fontawesome/solid/circle-question
    warning: fontawesome/solid/triangle-exclamation
    failure: fontawesome/solid/bomb
    danger: fontawesome/solid/skull
    bug: fontawesome/solid/robot
    example: fontawesome/solid/flask
    quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - content.code.select


plugins:
  - search
  - mkdocs-autoapi:
      autoapi_root: modules/
      autoapi_dir: src/pydashboard/modules
      autoapi_add_nav_entry: false
      autoapi_ignore:
        - demo.py
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src/pydashboard/containers
            - src/pydashboard/modules
          options:
            merge_init_into_class: true
            show_bases: false
            show_signature: false
            show_source: false
            show_root_toc_entry: false
            filters:
              - "^[A-Z]"
              - "^__init__"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption



nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Configuration file: config_file.md
  - Containers:
      - Basemodule: containers/basemodule.md
      - Tablemodule: containers/tablemodule.md
  - Modules: modules/
